// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package storage

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Transaction struct {
	TransactionID pgtype.UUID
	BuyerAddress  pgtype.Text
	SellerAddress pgtype.Text
	PostToken     string
	CallbackUrl   string
	SupplierID    string
	DemandID      string
}
