// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: queries.sql

package storage

import (
	"context"
)

const initializeTransaction = `-- name: InitializeTransaction :one
INSERT INTO transactions (post_token, supplier_id, demand_id)
VALUES ($1, $2, $3)
RETURNING transaction_id, buyer_address, seller_address, post_token, callback_url, supplier_id, demand_id
`

type InitializeTransactionParams struct {
	PostToken  string
	SupplierID string
	DemandID   string
}

func (q *Queries) InitializeTransaction(ctx context.Context, arg InitializeTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, initializeTransaction, arg.PostToken, arg.SupplierID, arg.DemandID)
	var i Transaction
	err := row.Scan(
		&i.TransactionID,
		&i.BuyerAddress,
		&i.SellerAddress,
		&i.PostToken,
		&i.CallbackUrl,
		&i.SupplierID,
		&i.DemandID,
	)
	return i, err
}
