services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: safe_send_db
    volumes:
      - ../../db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
